// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package gpuevent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpf_debugGpuKernelLaunchT struct {
	Flags   uint8
	PidInfo struct {
		HostPid uint32
		UserPid uint32
		Ns      uint32
	}
	KernFuncOff uint64
	GridX       int32
	GridY       int32
	GridZ       int32
	BlockX      int32
	BlockY      int32
	BlockZ      int32
	Stream      uint64
	Args        [16]uint64
	UstackSz    uint64
	Ustack      [128]uint64
}

type bpf_debugGpuMallocT struct {
	Flags   uint8
	Size    uint64
	PidInfo struct {
		HostPid uint32
		UserPid uint32
		Ns      uint32
	}
}

type bpf_debugStackDelta struct {
	AddrLow    uint16
	UnwindInfo uint16
}

type bpf_debugStackDeltaPageInfo struct {
	FirstDelta uint32
	NumDeltas  uint16
	MapID      uint16
}

type bpf_debugStackDeltaPageKey struct {
	FileID uint64
	Page   uint64
}

type bpf_debugUnwindInfo struct {
	Opcode      uint8
	FpOpcode    uint8
	MergeOpcode uint8
	_           [1]byte
	Param       int32
	FpParam     int32
}

// loadBpf_debug returns the embedded CollectionSpec for bpf_debug.
func loadBpf_debug() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_debugBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_debug: %w", err)
	}

	return spec, err
}

// loadBpf_debugObjects loads bpf_debug and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_debugObjects
//	*bpf_debugPrograms
//	*bpf_debugMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_debugObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_debug()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_debugSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_debugSpecs struct {
	bpf_debugProgramSpecs
	bpf_debugMapSpecs
}

// bpf_debugSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_debugProgramSpecs struct {
	HandleCudaLaunch *ebpf.ProgramSpec `ebpf:"handle_cuda_launch"`
	HandleCudaMalloc *ebpf.ProgramSpec `ebpf:"handle_cuda_malloc"`
}

// bpf_debugMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_debugMapSpecs struct {
	DebugEvents          *ebpf.MapSpec `ebpf:"debug_events"`
	ExeIdTo10StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_10_stack_deltas"`
	ExeIdTo11StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_11_stack_deltas"`
	ExeIdTo12StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_12_stack_deltas"`
	ExeIdTo13StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_13_stack_deltas"`
	ExeIdTo14StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_14_stack_deltas"`
	ExeIdTo15StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_15_stack_deltas"`
	ExeIdTo16StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_16_stack_deltas"`
	ExeIdTo17StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_17_stack_deltas"`
	ExeIdTo18StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_18_stack_deltas"`
	ExeIdTo19StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_19_stack_deltas"`
	ExeIdTo20StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_20_stack_deltas"`
	ExeIdTo21StackDeltas *ebpf.MapSpec `ebpf:"exe_id_to_21_stack_deltas"`
	ExeIdTo8StackDeltas  *ebpf.MapSpec `ebpf:"exe_id_to_8_stack_deltas"`
	ExeIdTo9StackDeltas  *ebpf.MapSpec `ebpf:"exe_id_to_9_stack_deltas"`
	InterpreterOffsets   *ebpf.MapSpec `ebpf:"interpreter_offsets"`
	KernelStackmap       *ebpf.MapSpec `ebpf:"kernel_stackmap"`
	PerCpuRecords        *ebpf.MapSpec `ebpf:"per_cpu_records"`
	PidCache             *ebpf.MapSpec `ebpf:"pid_cache"`
	PidPageToMappingInfo *ebpf.MapSpec `ebpf:"pid_page_to_mapping_info"`
	Rb                   *ebpf.MapSpec `ebpf:"rb"`
	StackDeltaArray      *ebpf.MapSpec `ebpf:"stack_delta_array"`
	StackDeltaPageToInfo *ebpf.MapSpec `ebpf:"stack_delta_page_to_info"`
	SystemConfig         *ebpf.MapSpec `ebpf:"system_config"`
	UnwindInfoArray      *ebpf.MapSpec `ebpf:"unwind_info_array"`
	ValidPids            *ebpf.MapSpec `ebpf:"valid_pids"`
}

// bpf_debugObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_debugObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_debugObjects struct {
	bpf_debugPrograms
	bpf_debugMaps
}

func (o *bpf_debugObjects) Close() error {
	return _Bpf_debugClose(
		&o.bpf_debugPrograms,
		&o.bpf_debugMaps,
	)
}

// bpf_debugMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_debugObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_debugMaps struct {
	DebugEvents          *ebpf.Map `ebpf:"debug_events"`
	ExeIdTo10StackDeltas *ebpf.Map `ebpf:"exe_id_to_10_stack_deltas"`
	ExeIdTo11StackDeltas *ebpf.Map `ebpf:"exe_id_to_11_stack_deltas"`
	ExeIdTo12StackDeltas *ebpf.Map `ebpf:"exe_id_to_12_stack_deltas"`
	ExeIdTo13StackDeltas *ebpf.Map `ebpf:"exe_id_to_13_stack_deltas"`
	ExeIdTo14StackDeltas *ebpf.Map `ebpf:"exe_id_to_14_stack_deltas"`
	ExeIdTo15StackDeltas *ebpf.Map `ebpf:"exe_id_to_15_stack_deltas"`
	ExeIdTo16StackDeltas *ebpf.Map `ebpf:"exe_id_to_16_stack_deltas"`
	ExeIdTo17StackDeltas *ebpf.Map `ebpf:"exe_id_to_17_stack_deltas"`
	ExeIdTo18StackDeltas *ebpf.Map `ebpf:"exe_id_to_18_stack_deltas"`
	ExeIdTo19StackDeltas *ebpf.Map `ebpf:"exe_id_to_19_stack_deltas"`
	ExeIdTo20StackDeltas *ebpf.Map `ebpf:"exe_id_to_20_stack_deltas"`
	ExeIdTo21StackDeltas *ebpf.Map `ebpf:"exe_id_to_21_stack_deltas"`
	ExeIdTo8StackDeltas  *ebpf.Map `ebpf:"exe_id_to_8_stack_deltas"`
	ExeIdTo9StackDeltas  *ebpf.Map `ebpf:"exe_id_to_9_stack_deltas"`
	InterpreterOffsets   *ebpf.Map `ebpf:"interpreter_offsets"`
	KernelStackmap       *ebpf.Map `ebpf:"kernel_stackmap"`
	PerCpuRecords        *ebpf.Map `ebpf:"per_cpu_records"`
	PidCache             *ebpf.Map `ebpf:"pid_cache"`
	PidPageToMappingInfo *ebpf.Map `ebpf:"pid_page_to_mapping_info"`
	Rb                   *ebpf.Map `ebpf:"rb"`
	StackDeltaArray      *ebpf.Map `ebpf:"stack_delta_array"`
	StackDeltaPageToInfo *ebpf.Map `ebpf:"stack_delta_page_to_info"`
	SystemConfig         *ebpf.Map `ebpf:"system_config"`
	UnwindInfoArray      *ebpf.Map `ebpf:"unwind_info_array"`
	ValidPids            *ebpf.Map `ebpf:"valid_pids"`
}

func (m *bpf_debugMaps) Close() error {
	return _Bpf_debugClose(
		m.DebugEvents,
		m.ExeIdTo10StackDeltas,
		m.ExeIdTo11StackDeltas,
		m.ExeIdTo12StackDeltas,
		m.ExeIdTo13StackDeltas,
		m.ExeIdTo14StackDeltas,
		m.ExeIdTo15StackDeltas,
		m.ExeIdTo16StackDeltas,
		m.ExeIdTo17StackDeltas,
		m.ExeIdTo18StackDeltas,
		m.ExeIdTo19StackDeltas,
		m.ExeIdTo20StackDeltas,
		m.ExeIdTo21StackDeltas,
		m.ExeIdTo8StackDeltas,
		m.ExeIdTo9StackDeltas,
		m.InterpreterOffsets,
		m.KernelStackmap,
		m.PerCpuRecords,
		m.PidCache,
		m.PidPageToMappingInfo,
		m.Rb,
		m.StackDeltaArray,
		m.StackDeltaPageToInfo,
		m.SystemConfig,
		m.UnwindInfoArray,
		m.ValidPids,
	)
}

// bpf_debugPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_debugObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_debugPrograms struct {
	HandleCudaLaunch *ebpf.Program `ebpf:"handle_cuda_launch"`
	HandleCudaMalloc *ebpf.Program `ebpf:"handle_cuda_malloc"`
}

func (p *bpf_debugPrograms) Close() error {
	return _Bpf_debugClose(
		p.HandleCudaLaunch,
		p.HandleCudaMalloc,
	)
}

func _Bpf_debugClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_debug_arm64_bpfel.o
var _Bpf_debugBytes []byte
